### ISSUE TITLE
RFQuack for Evil Crow RF

### ISSUE THREAD

**Issue by joelsernamoreno** [trendmicro/RFQuack#13] opened 2020-12-24 23:55 UTC
Hello!

I have spoken with Federico about implementing Evil Crow RF with RFQuack

Well... Evil Crow RF is a device with ESP32-PICO and two CC1101 modules

The problem with Evil Crow RF is that to upload any code it has to be set to QOUT or DOUT flash mode

So... when using your docker container it doesn't work because it needs this mode (esp32-PICO is continuously rebooted)

To fix this, you have to add **board_build.flash_mode = qout** in the RFQuack platformio.ini file

I have tried to do this in your example **RFQuack-esp32-CC1101-serial**, but when I run **pio run -t upload -d RFQuack-esp32-CC1101-serial** it gives many compilation errors.

Attached is a file with the errors
[output.txt](https://github.com/trendmicro/RFQuack/files/5740688/output.txt)

Can you help me implement RFQuack with Evil Crow RF?

Thank you!

**Comment by aguglie** [comment] 2020-12-25 11:29
Hi,
There's something wrong with the dependencies, I tried to compile it and got some errors.
To make it work: checkout the latest version from [rfquack/RFQuack](https://github.com/rfquack/RFQuack) and patch the RadioLib dependency using an old revision:

```diff
--- a/library.json
+++ b/library.json
@@ -52,7 +52,7 @@
         },
         {
             "name": "RadioLib",
-            "version": "https://github.com/rfquack/RadioLib"
+            "version": "https://github.com/rfquack/RadioLib#1da981a7cd3f6cbb3e20ea3f88bd7cf1b9e625e4"
         },
         {
         "name": "Base64",
```

I tested this by building the Docker container which automatically compiles all the examples.

**Comment by joelsernamoreno** [comment] 2020-12-25 12:41
Hello!

I tried the example of the last version of rfquack but it also gives error

How is the radiolib patch applied? Thank you

**Comment by aguglie** [comment] 2020-12-25 13:37
> How is the radiolib patch applied? Thank you

I just changed the version in `library.json` to reference a previous commit 😄 

In your logs there are some errors related to protobuf compiled files. Did you try to locally build the docker container after the above change? It may help in finding out if the problem is in the code or in the built environment (e.g.: protobuf compiler version.)

If the container builds successfully, you may just alter it to flash your board: after the setup phase the container does no more than [copying a default project](https://github.com/rfquack/RFQuack/blob/master/Dockerfile#L37) and [flash it using platform io](https://github.com/rfquack/RFQuack/blob/master/docker/my-entrypoint.sh).

@phretor do you know something more about those protobuf messages?

**Comment by joelsernamoreno** [comment] 2020-12-26 11:47
Hello!

I modified the file library.json with your change, now I receive these errors:
[output1.txt](https://github.com/trendmicro/RFQuack/files/5743042/output1.txt)

I also downloaded the latest version of RadioLib and put it in .platformio/lib/RadioLib, but I get these errors.
[output2.txt](https://github.com/trendmicro/RFQuack/files/5743043/output2.txt)

Thanks and Merry Christmas!!! :)

**Comment by aguglie** [comment] 2020-12-29 10:02
The first error should have been fixed by the RadioLib dependency change; is the library contained in `/home/joel/.platformio/lib/RadioLib` the same commit as `https://github.com/rfquack/RadioLib#1da981a7cd3f6cbb3e20ea3f88bd7cf1b9e625e4` ?

Did you try to build the docker container? 😃

**Comment by phretor** [comment] 2021-01-29 14:17
@Guglio95 do you mind sharing your CSW 2020 recording and configuration for RJ attack with @joelsernamoreno ? I'll send you an email about this.

@joelsernamoreno if you could comment on how you solved this, we could close this issue.

**Comment by joelsernamoreno** [comment] 2021-01-29 17:45
Hello @Guglio95 @phretor 

We update the Evil Crow RF hardware connections.

This allows to upload rfquack without flash dout or qout mode. Now it works

Then I ran into another problem, the first radio module was not working with RadioA, this uses pin D5 for CS and D2 for GDO0.

The second module (D27 for CS and D25 for GDO0) works fine for RadioA.

In testing I found that the first module only works if I configure it as RadioB. I think this is a problem with the RFQuack compatible hardware. Evil Crow RF has ESP32-PICO, it does not have ESP32.

This configuration works correctly:

- RADIOA: CS pin: D27 / IRQ pin: D25.
- RADIOB: CS pin: D5 / IRQ pin: D2

I have tested the modules on RX, one I have configured for 433.92MHz and the other for 315MHz. Now I can receive on both frequencies at the same time.

You can close this issue

I am waiting for the documentation of the RJ module, I know the syntax and the commands to use this, but I can't find the necessary parameters and configuration in the configuration files. You can send me this via mail

Thanks!

**Closed as completed** 2021-04-06 13:27 UTC
